# Use a slim Python image
FROM python:3.11-slim

# Set the working directory
WORKDIR /app

# Copy the dependency file and install dependencies
COPY ./requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code
COPY . /app

# Expose the port FastAPI runs on
EXPOSE 8000